import bcrypt from "bcryptjs";
const data = {
  users: [
    {
      name: "Justin Jake",
      email: "jake@example.com",
      password: bcrypt.hashSync("12345678"),
      isAdmin: true,
    },
    {
      name: "Alvin",
      email: "alvin@example.com",
      password: bcrypt.hashSync("alvincompra22"),
      isAdmin: false,
    },

    {
      name: "Panelist1",
      email: "panelist1@example.com",
      password: bcrypt.hashSync("Amanumberone"),
      isAdmin: true,
    },
    {
      name: "Panelist2",
      email: "panelist2@example.com",
      password: bcrypt.hashSync("Amanumberone"),
      isAdmin: false,
    },
    {
      name: "Panelist3",
      email: "panelist3@example.com",
      password: bcrypt.hashSync("Amanumberone"),
      isAdmin: true,
    },
    {
      name: "Panelist4",
      email: "panelist4@example.com",
      password: bcrypt.hashSync("Amanumberone"),
      isAdmin: false,
    },
  ],
  products: [
    //starts here
    {
      name: "Dentasix",
      slug: "denta",
      category: "Dog Treats",
      image: "/images/Dentastix.JPG",
      isFeatured: false,
      featuredImage: '"/images/Dentastix.JPG"',
      price: 100,
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: " For healthy metabolism ",
    },

    {
      name: "Top ration Tasty Bites",
      slug: "trtb",
      category: "Cat Food",
      image: "/images/Topration.jpg",
      isFeatured: true,
      featuredImage: '"/images/Topration.jpg"',
      price: 103,
      rating: 0,
      numReviews: 0,
      countInStock: 50,
      description:
        " Perfect for finicky cats or for those who consume too little water ",
    },
    {
      name: "Power Kitten 7kg",
      slug: "pk7kg",
      category: "Cat Dry Food",
      image: "/images/Power Kitten 7kg - cat dry food - 1350.jpg",
      isFeatured: true,
      featuredImage: '"/images/Power Kitten 7kg - cat dry food - 1350.jpg"',
      price: 1350,
      rating: 0,
      numReviews: 10,
      countInStock: 50,
      description:
        " Our smooth blend of tuna/chicken and fish oil recipe is perfect for cats of all life stages. Grain-Free, delicious and 100% Natural – this will be the most irresistible and ideal treat your cat will crave ",
    },

    {
      name: "Brit Premium Turkey",
      slug: "bpt",
      category: "Dog Wet Food",
      image: "/images/Brit Premium.jpg",
      isFeatured: true,
      featuredImage: '"/images/Brit Premium.jpg"',
      price: 96,
      rating: 0,
      numReviews: 0,
      countInStock: 50,
      description:
        " cat treats are created by nutritionists who are cat lovers and are made with goodness of carefully selected natural ingredients which contains no added colors or preservatives ",
    },
    {
      name: "Brit Premium",
      slug: "bp",
      category: "Dog Wet Food",
      image: "/images/Brit premium2.jpg",
      isFeatured: true,
      featuredImage: '"/images/Brit premium2.jpg"',
      price: 96,
      rating: 0,
      numReviews: 0,
      countInStock: 40,
      description:
        "Formulated for adult cats, made with fresh meat and Enriched with vitamins A, E and D3",
    },
    {
      name: "Meat Jerky  ",
      slug: "mj",
      category: "Dog Treats",
      image: "/images/Meat jerky.jpg",
      isFeatured: true,
      featuredImage: '"/images/Meat jerky.jpg"',
      price: 102,
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description:
        " With all the essential nutrients your cat needs for a healthy development, Feline Gourmet Cat food contains high quality protein and minerals to help build a strong immune system. ",
    },
    {
      name: "Dental Chew Milk",
      slug: "dcm",
      category: "Dog Treats",
      image: "/images/Dental Chew Milk.jpg",
      isFeatured: true,
      featuredImage: '"/images/Dental Chew Milk.jpg"',
      price: 38,
      rating: 0,
      numReviews: 0,
      countInStock: 50,
      description:
        " created to provide your cats with a complete meal that Is effortless and convenient ",
    },
    {
      name: "Brit Fish",
      slug: "bf",
      category: "Dog Wet Food",
      image: "/images/Brit Fish.jpg",
      isFeatured: true,
      featuredImage: '"/images/Brit Fish.jpg"',
      price: 85,
      rating: 0,
      numReviews: 0,
      countInStock: 60,
      description: " Protein as building blocks of body organs & tissues. ",
    },
    {
      name: "Teo Junior",
      slug: "tj",
      category: "Dog Wet Puppy Food",
      image: "/images/teo junior.jpg",
      isFeatured: true,
      featuredImage: '"/images/teo junior.jpg"',

      price: 73,
      rating: 0,
      numReviews: 0,
      countInStock: 60,
      description:
        " A tasty, appetizing premium cat food made with natural ingredients for healthy daily feline nutrition. ",
    },
    {
      name: "Brit fresh fish",
      slug: "fresh fish",
      category: "Dog Wet Food",
      image: "/images/brit fresh fish.jpg",
      isFeatured: true,
      featuredImage: '"/images/brit fresh fish.jpg"',
      price: 122,
      rating: 0,
      numReviews: 0,
      countInStock: 50,
      description:
        " Proven Hypoallergenic, with URINARY CARE FORMULA that is LESS SALT FORMULA with HIGH OMEGA 3 FATTY ACIDS that does not harm your pets kidney and essentially good for digestion. ",
    },
    {
      name: "Brit Premium Pork",
      slug: "pork brit",
      category: "Dog Wet Food",
      image: "/images/Brit Premium Pork.jpg",
      isFeatured: true,
      featuredImage: '"/images/Brit Premium Pork.jpg"',
      price: 90,
      rating: 0,
      numReviews: 0,
      countInStock: 50,
      description:
        " Lactating Mothers & Kittens , Improves digestion with better nutrient absorption",
    },
    {
      name: "Pedigree Meat Jerky",
      slug: "pedigreeMeatJerky",
      category: "Dog Treats",
      image: "/images/Pedigree meat jerky.jpg",
      isFeatured: true,
      featuredImage: '"/images/Pedigree meat jerky.jpg"',
      price: 102,
      rating: 0,
      numReviews: 0,
      countInStock: 50,
      description:
        " For healthy skin Excellent hair growth Boosts tissue repair Improves joint health ",
    },
    {
      name: "Feline Nutrition 6kg",
      slug: "feline-nut-7kg",
      category: "Cat Dry Food",
      image: "/images/top ration feline nutrition.jpg",
      isFeatured: true,
      featuredImage: '"/images/top ration feline nutrition.jpg"',
      price: 1365,
      rating: 0,
      numReviews: 0,
      countInStock: 50,
      description:
        "Special Cat is a 100% complete nutrition, formulated with highest quality of raw materials for cats of all life stages",
    },
    {
      name: "Kitkat Complete Cuisine",
      slug: "kitkta cuisine",
      category: "Cat Wet Food",
      image: "/images/Kitkat Complete Cuisine.jpg",
      isFeatured: false,
      featuredImage: '"/images/Kitkat Complete Cuisine.jpg"',
      price: 90,
      rating: 0,
      numReviews: 0,
      countInStock: 50,
      description:
        " Enriched with TAURINE, highly digestible, high palatability and for healthy shiny coat",
    },

    {
      name: "Zert Cheesecake Gellato",
      slug: "cheesecake",
      category: "Dog Treats",
      image: "/images/Zert Cheesecake Gellato.jpg",
      isFeatured: false,
      featuredImage: '"/images/Zert Cheesecake Gellato.jpg"',
      price: 170,
      rating: 0,
      numReviews: 0,
      countInStock: 50,
      description:
        "Helps maintain cat's uninary tract health, With vitamin A for perfect eye sight",
    },
    //stops here
    {
      name: "Whiskas Tuna 1kg",
      slug: "whiskas-1kg",
      category: "Cat Dry Food",
      image: "/images/whiskas.jpg",
      isFeatured: false,
      featuredImage: '"/images/whiskas.jpg"',
      price: 145,
      rating: 0,
      numReviews: 0,
      countInStock: 50,
      description:
        " It provides a gentle abrasive effect to help clean your cat's teeth and support healthy gums.",
    },
    {
      name: "Power Kitten",
      slug: "pkitten",
      category: "Cat Dry Food",
      image: "/images/Power.jpg",
      isFeatured: false,
      featuredImage: '"/images/Power.jpg"',
      price: 191,
      rating: 0,
      numReviews: 0,
      countInStock: 50,
      description:
        "Contains Protein for strong muscles Vitamins and minerals for body system to work effectively",
    },
    {
      name: "Pedigree Adult 1kg",
      slug: "pedigree1kg",
      category: "Dog Dry Food",
      image: "/images/Pedigree.jpg",
      isFeatured: false,
      featuredImage: '"/images/Pedigree.jpg"',
      price: 119,
      rating: 0,
      numReviews: 0,
      countInStock: 50,
      description: "Calcium and phosphorus for strong bones and teeth",
    },
    {
      name: "Pedigree puppy 1kg",
      slug: "pedigreepuppy",
      category: "Dog Dry Food",
      image: "/images/Pedigree2.jpg",
      isFeatured: false,
      featuredImage: '"/images/Pedigree2.jpg"',
      price: 144,
      rating: 0,
      numReviews: 0,
      countInStock: 50,
      description:
        "The immunity system from mother's milk is the best armor for puppies to help them grow up with proper physical and cognitive development.",
    },
    {
      name: "Tasty Bites 6kg",
      slug: "tb6kg",
      category: "Cat Dry Food",
      image: "/images/Tasty Bites.jpg",
      isFeatured: false,
      featuredImage: '"/images/Tasty Bites.jpg"',
      price: 1335,
      rating: 0,
      numReviews: 0,
      countInStock: 50,
      description: "The right choice after mother's milk for puppies",
    },
    {
      name: "Top ration High-Nutrition 6kg",
      slug: "trhn",
      category: "Dog Dry Food",
      image: "/images/TopRationHi-Nutrition18.14kg.png",
      isFeatured: false,
      featuredImage: '"/images/TopRationHi-Nutrition18.14kg.png"',
      price: 1250,
      rating: 0,
      numReviews: 0,
      countInStock: 50,
      description:
        "Helps improved healthy skin, Luxurios coats and lean mucles",
    },
    {
      name: "Brit Premium Lamb",
      slug: "bplflrv",
      category: "Dog Wet Food",
      image: "/images/Brit.jpg",
      isFeatured: false,
      featuredImage: '"/images/Brit.jpg"',
      price: 96,
      rating: 0,
      numReviews: 0,
      countInStock: 50,
      description: "Complete balance nutrition",
    },

    {
      name: "Brit Premium Beef ",
      slug: "beef flavor",
      category: "Dog Dry Food",
      image: "/images/Brit2.jpg",
      isFeatured: false,
      featuredImage: '"/images/Brit2.jpg"',
      price: 96,
      rating: 0,
      numReviews: 0,
      countInStock: 50,
      description:
        "Hypoallergenic formula and no artificial preservatives, colorings and flavorings",
    },
    {
      name: "Brit Premium Pork ",
      slug: "Pork Flavor",
      category: "Dog Dry Food",
      image: "/images/Brit3.jpg",
      isFeatured: false,
      featuredImage: '"/images/Brit3.jpg"',
      price: 96,
      rating: 0,
      numReviews: 0,
      countInStock: 50,
      description:
        " provide a healthy balanced diet for puppies up to 12 months of age or 18 months for large breed, and for pregnant or lactating dog.",
    },

    {
      name: "Pedigree Puppy 15kg",
      slug: "15kgpp",
      category: "Dog Dry Food",
      image: "/images/pedigreepuppy.jpg",
      isFeatured: false,
      featuredImage: '"/images/pedigreepuppy.jpg"',
      price: 2097,
      rating: 0,
      numReviews: 0,
      countInStock: 50,
      description:
        "It is specially formulated to prevent allergic reaction to food, help in development of the digestive system, prevent formation of free radicals, improve the immune system, reduce fecal odor and inprove skin and hair condition.",
    },

    {
      name: "Carnilove Soft Snack Carp",
      slug: "holistic-adul-1kg",
      category: "Dog Treats",
      image: "/images/carnilove2.jpg",
      isFeatured: false,
      featuredImage: '"/images/carnilove2.jpg"',
      price: 170,
      rating: 0,
      numReviews: 0,
      countInStock: 50,
      description:
        "Holistic Recipe Lamb and Rice Formula includes greeb tea, lamb meal and brewers rice, all high quality ingredients that provide a healthy balanced diet for adult dogs.",
    },
    {
      name: "Carnilove Soft Snack Sardines",
      slug: "sardinessnack",
      category: "Dog Treats",
      image: "/images/carnilove3.jpg",
      isFeatured: false,
      featuredImage: '"/images/carnilove3.jpg"',
      price: 170,
      rating: 0,
      numReviews: 0,
      countInStock: 50,
      description:
        "Guaranteed optimal ratio of Omega 3 & Omega 6 fatty acids for healthy skin and shiny coat",
    },

    {
      name: "Brit Pate Salmon",
      slug: "dog-adult-sack",
      category: "Dog Wet Food",
      image: "/images/Brit Pate2.jpg",
      isFeatured: false,
      featuredImage: '"/images/Brit Pate2.jpg"',
      price: 100,
      rating: 0,
      numReviews: 0,
      countInStock: 50,
      description:
        "Selection of whole grains provides enough protein, making pets quite energetic.",
    },
    {
      name: "Carnilove Salmon",
      slug: "for kitten",
      category: "Cat Dry Food",
      image: "/images/Carnilove5.jpg",
      isFeatured: false,
      featuredImage: '"/images/Carnilove5.jpg"',
      price: 850,
      rating: 0,
      numReviews: 0,
      countInStock: 50,
      description:
        "Improve immunity. Helping adult establish their immune system, added well-developed antioxidant complex.",
    },
    {
      name: "Brit Premium Adult 2kg",
      slug: "brit premium 2kg",
      category: "Cat Dry Food",
      image: "/images/Brit4.jpg",
      isFeatured: false,
      featuredImage: '"/images/Brit4.jpg"',
      price: 600,
      rating: 0,
      numReviews: 0,
      countInStock: 50,
      description:
        "It Comes with fresh meat, low cholesterol content, hypo-allergenic, highly digestible, it supplies high biological value proteins, like those found in lamb, and highly digestible carbohydrates, like those found in extruded rice.",
    },
    {
      name: "Kit Cat Tuna Hairball",
      slug: "catHairdball",
      category: "Cat Treats",
      image: "/images/Kit Cat.jpg",
      isFeatured: false,
      featuredImage: '"/images/Kit Cat.jpg"',
      price: 110,
      rating: 0,
      numReviews: 0,
      countInStock: 50,
      description:
        "A complete and balanced food for PUPPY (also for Pregnant & Lactation Performance) that require highly digestible foods that do not cause intestinal problems.",
    },
    //ends here latest
    {
      name: "Special Dog Adult 9kg",
      slug: "dog-special-sack",
      category: "Dog Dry Food",
      image: "/images/Special dog.jpg",
      isFeatured: false,
      featuredImage: '"/images/Special dog.jpg"',
      price: 1450,
      rating: 0,
      numReviews: 0,
      countInStock: 50,
      description:
        "Aozi is a pure natural organic food, pure natural healthy and safe food Support Full Range Growing  high quality protein",
    },
    {
      name: "Aozi Dog Puppy 1kg",
      slug: "dog-aozi-sack-1kg",
      category: "Dog Dry Food",
      image: "/images/AoziDogPuppy1kg.png",
      isFeatured: false,
      featuredImage: '"/images/AoziDogPuppy1kg.png"',
      price: 155,
      rating: 0,
      numReviews: 0,
      countInStock: 50,
      description:
        "For Puppy of All Breeds Younger than 10 months of age, also suitable for Pregnant and Lactating Dogs",
    },
    {
      name: "Brit Premium Dog in can Pork",
      slug: "Brit-premium",
      category: "Dog Wet Food",
      image: "/images/BritPremiumDogincanPork.png",
      isFeatured: false,
      featuredImage: '"/images/BritPremiumDogincanPork.png"',
      price: 96,
      rating: 0,
      numReviews: 0,
      countInStock: 50,
      description:
        "Complete food for adult dogs of all breeds meaty pate with trachea for dogs.",
    },
    {
      name: "Brit Premium Dog in Can Fish",
      slug: "Brit-premium-cat",
      category: "Dog Wet Food",
      image: "/images/BritPremiumDoginCanFish.png",
      isFeatured: false,
      featuredImage: '"/images/BritPremiumDoginCanFish.png"',
      price: 96,
      rating: 0,
      numReviews: 0,
      countInStock: 50,
      description: "With fish skin and enriched with salmon oil",
    },
    {
      name: "Brit Premium Dog in can Turkey",
      slug: "Brit-premium-turkey",
      category: "Dog Wet Food",
      image: "/images/BritPremiumDogincanTurkey.png",
      isFeatured: false,
      featuredImage: '"/images/BritPremiumDogincanTurkey.png"',
      price: 96,
      rating: 0,
      numReviews: 0,
      countInStock: 50,
      description:
        "Contains chamomile for sensitive digestion, salmon oil, fruit and herbs.",
    },
    {
      name: "Brit Premium Dog in can Beef",
      slug: "Brit-premium-beef",
      category: "Dog Wet Food",
      image: "/images/BritPremiumDogincanBeef.png",
      isFeatured: false,
      featuredImage: '"/images/BritPremiumDogincanBeef.png"',
      price: 96,
      rating: 0,
      numReviews: 0,
      countInStock: 50,
      description:
        " As a complete food or snack, or to add extra flavour to granules for adult dogs of all breeds. Improves food intake and hydration",
    },
    {
      name: "Montego Classic",
      slug: "Montego",
      category: "Dog Wet Food",
      image: "/images/MontegoClassic.png",
      isFeatured: false,
      featuredImage: '"/images/MontegoClassic.png"',
      price: 83,
      rating: 0,
      numReviews: 0,
      countInStock: 50,
      description:
        "Classic Wet Food provides a complete, balanced and enticingly delicious meal, or a tasty complement to your dog’s daily dry food diet.",
    },
    {
      name: "Special Dog Pate",
      slug: "special-pate",
      category: "Dog Wet Food",
      image: "/images/SpecialDogPate.png",
      isFeatured: false,
      featuredImage: '"/images/SpecialDogPate.png"',
      price: 90,
      rating: 0,
      numReviews: 0,
      countInStock: 50,
      description:
        "Paté premium in alutrays with beef tripe, ideal for daily diet of all breeds adult dogs. Steam cooked, without preservatives and added sugar.",
    },
    {
      name: "Teo in Can for Puppy",
      slug: "teo-in-can",
      category: "Dog Wet Food",
      image: "/images/TeoinCanforPuppy.png",
      isFeatured: false,
      featuredImage: '"/images/TeoinCanforPuppy.png"',
      price: 76,
      rating: 0,
      numReviews: 0,
      countInStock: 50,
      description:
        "Contains everything a puppy or a young dog needs. The food recipe supports immunity, healthy teeth and gums, healthy skin and hair and it also strengthens bones",
    },
    {
      name: "Teo in Can for Adult",
      slug: "teo-in-can-adult",
      category: "Dog Wet Food",
      image: "/images/TeoinCanforAdult.png",
      isFeatured: false,
      featuredImage: '"/images/TeoinCanforAdult.png"',
      price: 60,
      rating: 0,
      numReviews: 0,
      countInStock: 50,
      description:
        "a complete and tasty meal that can be a good source of nutrients for your dog",
    },
    //dont remove carnilove duck and pheasant
    {
      name: "Carnilove duck and pheasant ",
      slug: "carniLoveDuck",
      category: "Cat Dry Food",
      image:
        "/images/Carnilove duck and pheasant 3kg - 765 - Cat Dry food .jpg",
      isFeatured: false,
      featuredImage:
        '"/images/Carnilove duck and pheasant 3kg - 765 - Cat Dry food.jpg"',
      price: 765,
      rating: 0,
      numReviews: 0,
      countInStock: 30,
      description:
        " These irresistible treats are little crunchy shapes filled with delicious soft centres that cats dream about and all under two calories a pocket. ",
    },
    {
      name: "Brit Fresh Beef",
      slug: "brit-fresh-beef",
      category: "Dog Wet Food",
      image: "/images/BritFreshBeef.png",
      isFeatured: false,
      featuredImage: '"/images/BritFreshBeef.png"',
      price: 122,
      rating: 0,
      numReviews: 0,
      countInStock: 50,
      description:
        "A combined ancient grains like buckwheat, millet, and oats with traditional herbs, pumpkin, zucchini, and fruit to create a healthy menu that’s sure to please all canine lovers of delicious high-quality nutrition.",
    },
    {
      name: "Brit Pate and Meat  Salmon",
      slug: "brit-pate-salmon",
      category: "Dog Wet Food",
      image: "/images/BritPate_Meat Salmon.png",
      isFeatured: false,
      featuredImage: '"/images/BritPate_Meat Salmon.png"',
      price: 102,
      rating: 0,
      numReviews: 0,
      countInStock: 50,
      description:
        "A high content of quality meat and careful processing guarantee excellent flavour and aroma. A delicious combination of real chunks of meat and offal in pâté to perfectly satisfy even the most demanding canine gourmands",
    },
    {
      name: "Brit Mono Protein Beef",
      slug: "brit-mono-protein",
      category: "Dog Wet Food",
      image: "/images/BritMonoProteinBeef.png",
      isFeatured: false,
      featuredImage: '"/images/BritMonoProteinBeef.png"',
      price: 112,
      rating: 0,
      numReviews: 0,
      countInStock: 50,
      description:
        "Ideal for dogs with sensitive digestion, food allergies, or food intolerance.",
    },
    {
      name: "Meat Jerky Stick",
      slug: "meat-jery-stick",
      category: "Dog Treats",
      image: "/images/MeatJerkyStick.png",
      isFeatured: false,
      featuredImage: '"/images/MeatJerkyStick.png"',
      price: 102,
      rating: 0,
      numReviews: 0,
      countInStock: 50,
      description:
        "These are delicious sticks ideal for teating, rewarding and training your dog.",
    },

    {
      name: "Zert Gelato ",
      slug: "zert-gelato",
      category: "Dog Treats",
      image: "/images/ZertGelato.png",
      isFeatured: false,
      featuredImage: '"/images/ZertGelato.png"',
      price: 170,
      rating: 0,
      numReviews: 0,
      countInStock: 50,
      description:
        "Feed as a dessert after regular meals, can also be given as snack, treat, or as a reward.",
    },
    {
      name: "Carnilove Soft snack ",
      slug: "carnilove-soft-snack",
      category: "Dog Treats",
      image: "/images/CarniloveSoftsnackDogTreats.png",
      isFeatured: false,
      featuredImage: '"/images/CarniloveSoftsnackDogTreats.png"',
      price: 176,
      rating: 0,
      numReviews: 0,
      countInStock: 50,
      description:
        "Exotic Meat flavour! Delicious soft snack suitable for all dogs for healthy teeth and gums. A semi moist snack for ultimate tasty treat and perfect compliment to your dog’s regular diet.",
    },
  ],
};

export default data;
