import bcrypt from "bcryptjs";
const data = {
  users: [
    {
      name: "Justin Jake",
      email: "jake@example.com",
      password: bcrypt.hashSync("12345678"),
      isAdmin: true,
    },
    {
      name: "Alvin",
      email: "alvin@example.com",
      password: bcrypt.hashSync("alvincompra22"),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Aozi Adult",
      slug: "free-shirt1",
      category: "Dog Food",
      image: "/images/product1.jpg",
      isFeatured: false,
      featuredImage: '"/images/product1.jpg"',
      price: 150,
      rating: 0,
      numReviews: 10,
      countInStock: 20,
      description: "Dog Food",
    },
    {
      name: "Aozi Puppy",
      slug: "free-shirt2",
      category: "Dog FOod",
      image: "/images/product2.jpg",
      isFeatured: false,
      featuredImage: '"/images/product2.jpg"',
      price: 150,
      rating: 0,
      numReviews: 10,
      countInStock: 20,
      description: "Dog Food",
    },
    {
      name: "Top Ration",
      slug: "free-shirt4",
      category: "Dog Food",
      image: "/images/product3.jpg",
      isFeatured: true,
      featuredImage: '"/images/product3.jpg"',
      price: 150,
      rating: 0,
      numReviews: 10,
      countInStock: 20,
      description: "Dog Food",
    },
    {
      name: "Pedigree Adult",
      slug: "free-shir3t",
      category: "Cat Food",
      image: "/images/product4.jpg",
      isFeatured: true,
      featuredImage: '"/images/product4.jpg"',
      price: 150,
      rating: 0,
      numReviews: 10,
      countInStock: 20,
      description: "Dog Food",
    },
    {
      name: "Pedigree Puppy",
      slug: "free-shirt22",
      category: "Dog Food",
      image: "/images/product5.jpg",
      isFeatured: true,
      featuredImage: '"/images/product5.jpg"',
      price: 150,
      rating: 0,
      numReviews: 10,
      countInStock: 20,
      description: "Dog Food",
    },
    {
      name: "Carp",
      slug: "Soft Snacks",
      category: "Dog Food",
      image: "/images/CarniLove.jpg",
      isFeatured: true,
      featuredImage: '"/images/CarniLove.jpg"',
      price: 150,
      rating: 0,
      numReviews: 10,
      countInStock: 20,
      description: "Soft Snacks for all dogs",
    },
    {
      name: "Mackerel ",
      slug: "Crunchy Snacks",
      category: "Dog Food",
      image: "/images/CarniLove1.jpg",
      isFeatured: true,
      featuredImage: '"/images/CarniLove1.jpg"',
      price: 150,
      rating: 0,
      numReviews: 10,
      countInStock: 20,
      description: "Crunchy Snacks for all dogs",
    },
    {
      name: "Dill",
      slug: "Trout",
      category: "Dog Food",
      image: "/images/CarniLove3.jpg",
      isFeatured: true,
      featuredImage: '"/images/CarniLove3.jpg"',

      price: 150,
      rating: 0,
      numReviews: 10,
      countInStock: 20,
      description: "Soft Snacks for all dogs",
    },
    {
      name: "Wild Garlic",
      slug: "Sardines",
      category: "Dog Food",
      image: "/images/CarniLove2.jpg",
      isFeatured: true,
      featuredImage: '"/images/CarniLove2.jpg"',
      price: 150,
      rating: 0,
      numReviews: 10,
      countInStock: 20,
      description: "Soft Snacks for all dogs",
    },
    {
      name: "Wild Garlic",
      slug: "Sardines2",
      category: "Dog Food",
      image: "/images/CarniLove2.jpg",
      isFeatured: true,
      featuredImage: '"/images/CarniLove2.jpg"',

      price: 150,
      rating: 0,
      numReviews: 10,
      countInStock: 20,
      description: "Soft Snacks for all dogs",
    },
    {
      name: "Wild Garlic",
      slug: "Sardines1",
      category: "Dog Food",
      image: "/images/CarniLove2.jpg",
      isFeatured: true,
      featuredImage: '"/images/CarniLove.jpg"',
      price: 150,
      rating: 0,
      numReviews: 10,
      countInStock: 20,
      description: "Soft Snacks for all dogs",
    },
    {
      name: "Wild Garlic",
      slug: "Sardines5",
      category: "Dog Food",
      image: "/images/CarniLove2.jpg",
      isFeatured: true,
      featuredImage: '"/images/product2.jpg"',
      price: 150,
      rating: 0,
      numReviews: 10,
      countInStock: 20,
      description: "Soft Snacks for all dogs",
    },
  ],
};
export default data;
